@startuml
title Fluxo: Atualização de configuração

!pragma teoz true
box "IF" #LightBlue
   box "Motor Qualidade de Dados" #D5E8D4
     participant ConfigurationManager #7EA6E0
   end box
end box

box "PERIMETRO CENTRAL" #D5E8D4
   box "MQD - SERVER" #LightBlue
     participant API #B1DDF0
     participant AUTH #B1DDF0
   end box
end box

note over ConfigurationManager 
   1. A cada 6 horas, o MQD
      executa o processo de atualização 
      das configurações
end note

ConfigurationManager -> AUTH: Request Token
AUTH -> ConfigurationManager: JWT Token

ConfigurationManager -> API : Request Configuration
API -> ConfigurationManager: ConfigurationSettings.json

ConfigurationManager -> ConfigurationManager: Check Configuration

note over ConfigurationManager 
   casso a configuração seja differente
   da atual, é iniciado o processo de 
   atualização detalhada
end note

alt Configuration is different
   loop messages.APIGroups times
      ConfigurationManager -> API: APIGroup
      API -> ConfigurationManager :APIGroup Configuration
   end
  
   ConfigurationManager -> ConfigurationManager : Update Configuration Settings

end

@enduml