FROM golang:alpine as builder
RUN apk update && apk add --no-cache git
WORKDIR /src
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN ls -la ./
RUN go build -o ./out/dist ./API
CMD ./out/dist