version: '3'
services:
  mqd-client:
    image: mqd-client:latest
    ports:
      - "8080:8080"
    environment:
      - API_PORT=:8080
      - SERVER_ORG_ID=09b20d09-bf30-4497-938e-b0ead8ce9629
      #- REPORT_EXECUTION_WINDOW=30 # Optional Variable
      #- REPORT_EXECUTION_NUMBER= 200000 # Optional Variable
      - ENVIRONMENT=DEBUG
      - LOGGING_LEVEL=DEBUG
      - APPLICATION_MODE=RECEIVER  #TRANSMITTER / RECEIVER
      - PROXY_URL=http://127.0.0.1:8082
    network_mode: "host"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M
  proxy:
    image: nginx
    ports:
      - "8082:80"
    volumes:
     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro  # Adjust paths as needed
     - ./certificates:/etc/ssl  # Adjust paths as needed
