openapi: 3.0.0
info:
  title: Dynamic Data Schema
  version: 1.0
components:
  schemas:
    DynamicStruct:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
        email:
          type: string
          format: email
      required:
        - name
        - age
        - email